github.com:
    oauth_token: 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
    user: frdelage-ext_afklm
    git_protocol: https
    users:
        frdelage-ext_afklm:
            oauth_token: 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
